language: python
python:
    - 2.7
    - 3.5
install:
    - pip install -U setuptools
    - python bootstrap.py
    - ./bin/buildout
before_script:
    - ./bin/flake8 emoticons
script:
    - ./bin/test-and-cover
after_success:
    - ./bin/coveralls
