language: python
python:
    - 2.7
    - 3.4
    - 3.5
env:
    - DJANGO=1.9
install:
    - pip install -U setuptools
    - python bootstrap.py
    - ./bin/buildout versions:django=$DJANGO
before_script:
    - ./bin/flake8 emoticons
script:
    - ./bin/test-and-cover
after_success:
    - ./bin/coveralls
