language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
env:
    - DJANGO=1.4
    - DJANGO=1.5
    - DJANGO=1.6
matrix:
    exclude:
        - python: 3.2
          env: DJANGO=1.4
        - python: 3.3
          env: DJANGO=1.4
install:
    - pip install -U setuptools
    - python bootstrap.py
    - ./bin/buildout versions:django=$DJANGO
before_script:
    - ./bin/flake8 emoticons
script:
    - ./bin/test-and-cover
after_success:
    - ./bin/coveralls
